### ISSUE TITLE
Downgrading shouldn't be always possible

### ISSUE THREAD

**Issue by michaltakac** [michaltakac/meteor-saas-braintree#3]
On Crater.io where Ryan Glover posted link to this repo - https://crater.io/posts/GzFfnAmQ8NmKJ77cr - user **fvg** pointed out that "when you cancel the pro subscription and then re-subscribe using a standard subscription, you can get **_15 of 5 lists used**_", which is bad.

**Comment by DevanB** [comment]
This is still an outstanding issue. Do you have any plans to fix this?

**Comment by michaltakac** [comment]
I'm currently swamped with work, but I'm accepting PR.
Will take a look at it on first week of new year.
