### ISSUE TITLE
creating a customer

### ISSUE THREAD

**Issue by adamwhitlock1** [michaltakac/meteor-saas-braintree#7]
My cloned app repo is not able to create new users Via meteor on mac.

I am getting a server side error reported as:

`Exception in delivering result of invoking 'btCreateCustomer': TypeError: Cannot read property 'id' of undefined`

on `app/server/methods/signup.js:45:47`

there is something on the creation of the new user that is keeping the registration process to complete

**Comment by adamwhitlock1** [comment]
I fixed the issue I was having with the customer creation (settings just werent correct), and I ran into another issue. The issue originated from iron router, and there is a reported issue with the lower versions of iron router with new versions of chrome and other browsers.

So if anyone receives the error of "hookWithOptions" already exists, or something similar then try

`meteor add iron:middleware-stack@1.1.0`

the package update should fix the router issue. Thanks for this example michaltakac! I appreciate the work you have done on this. One question though is How hard would this example be to port over to using FlowRouter instead of iron router? I have an app with flow router that I would like to use this payment code for. Thanks Again!

**Comment by michaltakac** [comment]
It shouldn't be hard to refractor this to use FlowRouter, just need to move subscriptions from router level to template level...

``` javascript
Template.templatename.onCreated(function() {
    this.subscribe('publicationName');
    // ...
});
```

...use `useraccounts:core` and `useraccounts:flow-routing` for login/register forms and then use `AccountsTemplates.ensureSignedIn` for routes that needs to be protected by login like this:

``` javascript
FlowRouter.route('/private', {
  triggersEnter: [AccountsTemplates.ensureSignedIn],
  action: function() {
    BlazeLayout.render(...);
  }
});
```

and pretty much change all routes to use FlowRouter. For Braintree webhook functions to work, there are server routes in `/server/routes.js` that needs to be refractored to use another package for server routing, like `meteorhacks:picker` https://atmospherejs.com/meteorhacks/picker. Hope it helps and if you want, feel free to contribute!

**Comment by adamwhitlock1** [comment]
thanks for the advice ill have to give it a shot and report back

**Comment by worldplayinc** [comment]
I am getting the same error:
"Exception in delivering result of invoking 'btCreateCustomer': TypeError: Cannot read property 'id' of undefined"
Please help
